[extend]
useDefault = true

[allowlist]
description = "global allow list"

# ignoring historical secrets from past commits
# (not present in the current codebase)
commits = [
  "9c8b32139b73111b618fc946a7f64355e8429423",
]
