repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
        stages: [ commit ]
  - repo: local
    hooks:
      - id: helm-unittest
        name: Helm Unittest
        entry: helm unittest charts/snyk-broker
        language: system
        files: ^charts/snyk-broker/
        pass_filenames: false
        stages: [pre-commit]
