apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.scmType}}-broker-service{{if not .Values.disableSuffixes }}-{{ .Release.Name }}{{ end }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.brokerType }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.container.containerPort }}
  selector:
    {{- include "snyk-broker.selectorLabels" . | nindent 4 }}
