{{- $autoscaling := .Values.autoscaling | default dict -}}
{{- $cpuType := ternary "Utilization" "Value" ( eq $autoscaling.cpu.type "Utilization" ) -}}
{{- $memoryType := ternary "Utilization" "Value" ( eq $autoscaling.memory.type "Utilization" ) -}}
{{- if ( and $autoscaling.enabled .Values.highAvailabilityMode.enabled ) -}}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: "{{ .Values.scmType}}-broker{{if not .Values.disableSuffixes }}-{{ .Release.Name }}{{ end }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "{{ .Values.scmType}}-broker{{if not .Values.disableSuffixes }}-{{ .Release.Name }}{{ end }}"
  minReplicas: {{ $autoscaling.minReplicas | default 2 }}
  maxReplicas: {{ $autoscaling.maxReplicas | default 4 }}
  metrics:
  {{- if $autoscaling.cpu.enabled }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: {{ $autoscaling.cpu.type }}
        {{ printf "average%s" $cpuType }}: {{ $autoscaling.cpu.value }}
  {{- end -}}
  {{- if $autoscaling.memory.enabled }}
  - type: Resource
    resource:
      name: memory
      target:
        type: {{ $autoscaling.memory.type }}
        {{ printf "average%s" $memoryType }}: {{ $autoscaling.memory.value }}
  {{- end -}}
{{- end -}}
