{{- if .Values.httpsCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snyk-broker.fullname" . }}-httpscert-configmap{{if not .Values.disableSuffixes }}-{{ .Release.Name }}{{ end }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-broker.labels" . | nindent 4 }}
data:
{{ (.Files.Glob .Values.httpsCert).AsConfig | nindent 2 }}
{{- end }}